version: "3.1"

services:
  boot:
    networks:
      - test
    ports:
      - "3000:3000"
      - "7888-7890:7888-7890"
    command: dev
    depends_on:
      - firefox

  firefox:
    image: selenium/standalone-firefox-debug
    networks:
      - test
    ports:
      - "5900:5900"

networks:
  test:
